/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function measureHashesPerSecond(): number
export function repeatingHash(passcode: string, numHashes: number): string
export function bruteForceHash(hash: string, numHashes: number): string | null
